svn propset svn:eol-style native src/other/stepcode/CONTRIBUTING.md 
svn propset svn:eol-style native src/other/stepcode/INTENT.md 
svn propset svn:eol-style native src/other/stepcode/data/STEPTools_merged_schema/modified_step_merged_cad_schema.exp.broken 
svn propset svn:eol-style native src/other/stepcode/data/ap209/ATS1-out.stp 
svn propset svn:eol-style native src/other/stepcode/data/ap209/ATS10-out.stp 
svn propset svn:eol-style native src/other/stepcode/data/ap209/ATS10Mod0-out.stp 
svn propset svn:eol-style native src/other/stepcode/data/ap209/ATS10Mod0-outresult.stp 
svn propset svn:eol-style native src/other/stepcode/data/ap209/ATS1Mod0-out.stp 
svn propset svn:eol-style native src/other/stepcode/data/ap209/ATS1Mod0-outresult.stp 
svn propset svn:eol-style native src/other/stepcode/data/ap209/ATS2-out.stp 
svn propset svn:eol-style native src/other/stepcode/data/ap209/ATS2Mod0-out.stp 
svn propset svn:eol-style native src/other/stepcode/data/ap209/ATS2Mod0-outresult.stp 
svn propset svn:eol-style native src/other/stepcode/data/ap209/ATS3-out.stp 
svn propset svn:eol-style native src/other/stepcode/data/ap209/ATS3Mod0-out.stp 
svn propset svn:eol-style native src/other/stepcode/data/ap209/ATS3Mod0-outresult.stp 
svn propset svn:eol-style native src/other/stepcode/data/ap209/ATS4-out.stp 
svn propset svn:eol-style native src/other/stepcode/data/ap209/ATS4Mod0-out.stp 
svn propset svn:eol-style native src/other/stepcode/data/ap209/ATS4Mod0-outresult.stp 
svn propset svn:eol-style native src/other/stepcode/data/ap209/ATS7-out.stp 
svn propset svn:eol-style native src/other/stepcode/data/ap209/ATS7Mod0-out.stp 
svn propset svn:eol-style native src/other/stepcode/data/ap209/ATS7Mod0-outresult.stp 
svn propset svn:eol-style native src/other/stepcode/data/ap209/ATS8-out.stp 
svn propset svn:eol-style native src/other/stepcode/data/ap209/ATS8Mod0-out.stp 
svn propset svn:eol-style native src/other/stepcode/data/ap209/ATS8Mod0-outresult.stp 
svn propset svn:eol-style native src/other/stepcode/data/ap209/ap209_N8334_mim_lf.exp 
svn propset svn:eol-style native src/other/stepcode/data/ap210e3/ap210e3_n8232_mim_lf.exp 
svn propset svn:eol-style native src/other/stepcode/data/ap242/242_n8324_mim_lf.exp 
svn propset svn:eol-style native src/other/stepcode/misc/summarize-appveyor-log.go 
svn propset svn:eol-style native src/other/stepcode/src/exp2cxx/test/missing_init.exp 
svn propset svn:eol-style native src/other/stepcode/src/exp2python/python/.gitignore 
svn propset svn:eol-style native src/other/stepcode/src/exppp/test/exppp_div_slash.exp 
svn propset svn:eol-style native src/other/stepcode/src/exppp/test/exppp_lost_var.exp 
svn propset svn:eol-style native src/other/stepcode/src/exppp/test/exppp_problems.exp 
svn propset svn:eol-style native src/other/stepcode/src/exppp/test/exppp_supertype_andor.exp 
svn propset svn:eol-style native src/other/stepcode/src/express/test/plib_parse_err.exp 
svn propset svn:eol-style native src/other/stepcode/test/p21/select_segfault_2.stp 
svn propset svn:eol-style native src/other/stepcode/test/p21/test_inherit_inverse.p21 
svn propset svn:eol-style native src/other/stepcode/test/unitary_schemas/inherit_inverse.exp 
svn propset svn:eol-style native src/other/stepcode/test/unitary_schemas/inverse_bug.exp 
svn propset svn:eol-style native src/other/stepcode/test/unitary_schemas/inverse_qualifiers.exp 
svn propset svn:eol-style native src/other/stepcode/test/unitary_schemas/numbered_inverse_attr.exp 
svn propset svn:eol-style native src/other/stepcode/test/unitary_schemas/select_segfault_2.exp 
svn propset svn:eol-style native src/other/stepcode/test/unitary_schemas/unique_qualifiers.exp 
svn propset svn:eol-style native src/other/stepcode/test/unitary_schemas/ur_redecl.exp 

