name: BRL-CAD

on: [push]

jobs:
  build-mac:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - uses: lukka/get-cmake@latest
    - name: configure
      run: mkdir build && cd build && cmake --version && cmake .. -DENABLE_ALL=ON && more CMakeCache.txt
    - name: build
      run: cd build && make libicv VERBOSE=1 && ls -R
    - name: configure2
      run: cd build && rm CMakeCache.txt && cmake .. && more CMakeCache.txt && ls -R
    - name: build2
      run: cd build && make clean &&  make libicv VERBOSE=1 --build build -v && ls -R
