name: BRL-CAD

on: [push]

jobs:
  build-mac:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - uses: lukka/get-cmake@latest
    - name: configure
      run: mkdir build && cd build && cmake --version && cmake .. && more CMakeCache.txt && ls -R
    - name: build
      run: cd build && make distcheck
    - name: info
      run: cd build && more distcheck-enableall_debug.log && more distcheck-enableall_release.log
