name: BRL-CAD

on: [push]

jobs:
  build-mac:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - uses: lukka/get-cmake@latest
    - name: configure
      run: mkdir build && cd build && cmake --version && cmake .. -DENABLE_ALL=ON && ls -R
    - name: build
      run: cd build && make VERBOSE=1 && ls -R
    - name: test
      run: cd build && make check VERBOSE=1
