name: BRL-CAD

on: [push]

jobs:
  build-ubuntu:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - uses: lukka/get-cmake@latest
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && cmake --build check
